project:
  type: website
  output-dir: docs

website:
  title: "UO Acute Care Simulation Lab"

  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: simulations/sim1/index.qmd
        text: Simulation 1

format:
  html:
    theme: cosmo
    toc: false
    page-layout: full
    css: styles.css